services:
  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - 5000:5000
    environment:
      - AWS_ACCESS_KEY_ID=eJD2Z4bScmngoet8sfAk
      - AWS_SECRET_ACCESS_KEY=khmHFyRDwuA4ognM5FRLEVFQ9fV09UxWW3pXAtNe
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
    depends_on:
      - postgres
      - minio
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mlflow
      - POSTGRES_PASSWORD=mlflow123
      - POSTGRES_DB=mlflow
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio_user
      - MINIO_ROOT_PASSWORD=minio_pwd
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
  
  dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./src:/workspace/src
    depends_on:
      - mlflow

volumes:
  postgres_data:
  minio_data:
